language: rust
sudo: false

cache:
  cargo: true
  directories:
     - $HOME/.xargo

addons:
  apt:
    packages:
      - binutils-arm-none-eabi
      - gcc-arm-linux-gnueabi

rust:
  - nightly

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup target add arm-unknown-linux-gnueabi
  - rustup component add rust-src
  - rustup component add rustfmt-preview
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - cargo install xargo || echo "xargo already installed"

script:
  - |
      xargo build && xargo test

# branches:
#   only:
#     - master

notifications:
  email:
    on_success: never